{
 "title": "Crawler monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Кол-во обработаных страниц",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "crawler_pages_parsed{instance=\"crawler-app:8000\",job=\"crawler-app\"}"
    }
   ]
  },
  {
   "title": "Кол-во обработанных запросов",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "web_pages_served{instance=\"crawler-ui:8000\",job=\"crawler-ui\"}"
    }
   ]
  },
  {
   "title": "Время на Подключение и Обработку",
   "type": "graph",
   "description": "crawler_site_connection_time - время затраченное ботом на подключение к веб-сайту и загрузку веб-страницы\ncrawler_page_parse_time - время затраченное ботом на обработку содержимого веб-страницы",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(crawler_site_connection_time_bucket[5m])) by (le))\n"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(crawler_page_parse_time_bucket[5m])) by (le))\n"
    }
   ]
  },
  {
   "title": "Время генерации веб-страниц",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(web_page_gen_time_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Кол-во подключений к mongodb",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_connections{instance=\"mongodb-exporter:9216\",job=\"mongodb\",state=\"current\"}"
    }
   ]
  }
 ]
}