---
image: docker:stable

stages:
  - build
  - test
  - review
  - stage
  - production

variables:
  REGISTRY_URL: http://192.168.88.12/
  DOCKER_DRIVER: overlay2
  APP_NAME: crawler-app # и имя директории тоже
  UI_NAME: crawler-ui # и имя директории тоже
  TAG_NAME: test

###############################################
############### Build section ##################
###############################################

build_ui_job:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  environment:
    name: testing/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.192.168.88.12
  only:
    changes:
      - .gitlab-ci.yml
      - $UI_NAME
  except:
    - master
  script:
    - echo "Building and push the $CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" # добавляются в вебе переменные 
    - docker build -t "$CI_REGISTRY_USER/$UI_NAME:$TAG_NAME" $UI_NAME/
    - docker push "$CI_REGISTRY_USER/$UI_NAME:$TAG_NAME"

build_crawler_job:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  environment:
    name: testing/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.192.168.88.12
  only:
    changes:
      - .gitlab-ci.yml
      - $APP_NAME
  except:
    - master
  script:
    - echo "Building and push the $CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - docker build -t "$CI_REGISTRY_USER/$APP_NAME:$TAG_NAME" $APP_NAME/
    - docker push "$CI_REGISTRY_USER/$APP_NAME:$TAG_NAME"

###############################################
############### Test code section ##################
###############################################

#test_ui_py2:
#  stage: test
#  image: python:2-alpine
#  environment:
#    name: testing/$CI_COMMIT_REF_NAME
#    url: https://$CI_ENVIRONMENT_SLUG.192.168.88.12
#  only:
#    - branches
#  except:
#    - master
#    - tags
#  script:
#    - pip install -r ui/requirements.txt -r ui/requirements-test.txt
#    - cd ui 
#    - python -m unittest discover -s tests/
#    - coverage run -m unittest discover -s tests/
#    - coverage report --include ui/ui.py

#test_crawler_py2:
#  stage: test
#  image: python:2-alpine
#  environment:
#    name: testing/$CI_COMMIT_REF_NAME
#    url: https://$CI_ENVIRONMENT_SLUG.192.168.88.12
#  only:
#    - branches
#  except:
#    - master
#    - tags
#  script:
#    - pip install --upgrade pip
#    - pip install -r crawler/requirements.txt -r crawler/requirements-test.txt
#    - cd crawler 
#    - python -m unittest discover -s tests/ 
#    - coverage run -m unittest discover -s tests/ 
#    - coverage report --include crawler/crawler.py


test_ui_py3:
  stage: test
  image: python:3.6.0-alpine
  environment:
    name: testing/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.192.168.88.12
  only:
    - branches
  except:
    - master
    - tags
  script:
    - pip3 install -r ui/requirements.txt -r ui/requirements-test.txt
    - cd ui 
    - python3 -m unittest discover -s tests/
    - coverage3 run -m unittest discover -s tests/
    - coverage3 report --include ui/ui.py

test_crawler_py3:
  stage: test
  image: python:3.6.0-alpine
  environment:
    name: testing/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.192.168.88.12
  only:
    - branches
  except:
    - master
    - tags
  script:
    - pip3 install --upgrade pip
    - pip3 install -r crawler/requirements.txt -r crawler/requirements-test.txt
    - cd crawler 
    - python3 -m unittest discover -s tests/ 
    - coverage3 run -m unittest discover -s tests/ 
    - coverage3 report --include crawler/crawler.py

test_ui_container:
  stage: test
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - docker pull "$CI_REGISTRY_USER/$UI_NAME:$TAG_NAME"
    - docker run "$CI_REGISTRY_USER/$UI_NAME:$TAG_NAME" python3 -m unittest discover -s tests/
    - docker run "$CI_REGISTRY_USER/$UI_NAME:$TAG_NAME" coverage3 run -m unittest discover -s tests/
    - docker run "$CI_REGISTRY_USER/$UI_NAME:$TAG_NAME" coverage3 report --include ui/ui.py

test_crawler_container:
  stage: test
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - docker pull "$CI_REGISTRY_USER/$APP_NAME:$TAG_NAME"
    - docker run "$CI_REGISTRY_USER/$APP_NAME:$TAG_NAME" python3 -m unittest discover -s tests/
    - docker run "$CI_REGISTRY_USER/$UI_NAME:$TAG_NAME" coverage3 run -m unittest discover -s tests/
    - docker run "$CI_REGISTRY_USER/$UI_NAME:$TAG_NAME" coverage3 report --include crawler/crawler.py

###############################################
############### Review section ##################
###############################################

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.192.168.88.12

branch review:
  stage: review
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.192.168.88.12
  only:
    - branches
  except:
    - master
    - tags

###############################################
############### Staging section ##################
###############################################

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy to staging'
  environment:
    name: stage
    url: https://beta.192.168.88.12

###############################################
############### Production section ##################
###############################################

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
    - master
  script:
    - echo 'Deploy to production'
  environment: #куда деплоить 
    name: production
    url: https://192.168.88.12
