---
image: docker:stable

stages:
  - build
  - test
  - review
  - stage
  - production

variables:
  REGISTRY_URL: http://192.168.88.12/
  DOCKER_DRIVER: overlay2
  PROJECT_NAME: crawler

###############################################
############### Build section ##################
###############################################

build_ui_job:
  stage: build
  image: docker:stable
  environment:
    name: testing/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master
    - tags
  script:
    - echo "Building ui in $CI_ENVIRONMENT_SLUG"
    - docker build -t ${USERNAME}/ui:${UI_VER} ui/

build_crawler_job:
  stage: build
  image: docker:stable
  environment:
    name: testing/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master
    - tags
  script:
    - echo "Building crawler in $CI_ENVIRONMENT_SLUG"
    - docker build -t ${USERNAME}/crawler:${CRAWLER_VER} crawler/

###############################################
############### Test section ##################
###############################################

test_ui_py2:
  stage: test
  image: python:2-alpine
  environment:
    name: testing/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master
    - tags
  script:
    - echo "Testing ui in $CI_ENVIRONMENT_SLUG"
    - pip install -r ui/requirements.txt -r ui/requirements-test.txt
    - cd ui 
    - python -m unittest discover -s tests/
    - coverage run -m unittest discover -s tests/
    - coverage report --include ui/ui.py

test_crawler_py2:
  stage: test
  image: python:2-alpine
  environment:
    name: testing/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master
    - tags
  script:
    - echo "Testing crawler in $CI_ENVIRONMENT_SLUG"
    - pip install --upgrade pip
    - pip install -r crawler/requirements.txt -r crawler/requirements-test.txt functools
    - cd crawler 
    - python -m unittest discover -s tests/ 
    - coverage run -m unittest discover -s tests/ 
    - coverage report --include crawler/crawler.py


test_ui_py3:
  stage: test
  image: python:alpine
  environment:
    name: testing/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master
    - tags
  script:
    - echo "Testing ui in $CI_ENVIRONMENT_SLUG"
    - pip3 install -r ui/requirements.txt -r ui/requirements-test.txt
    - cd ui 
    - python3 -m unittest discover -s tests/
    - coverage3 run -m unittest discover -s tests/
    - coverage3 report --include ui/ui.py

test_crawler_py3:
  stage: test
  image: python:alpine
  environment:
    name: testing/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master
    - tags
  script:
    - echo "Testing crawler in $CI_ENVIRONMENT_SLUG"
    - pip3 install --upgrade pip
    - pip3 install -r crawler/requirements.txt -r crawler/requirements-test.txt
    - cd crawler 
    - python3 -m unittest discover -s tests/ 
    - coverage3 run -m unittest discover -s tests/ 
    - coverage3 report --include crawler/crawler.py

###############################################
############### Review section ##################
###############################################

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

branch review:
  stage: review
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master
    - tags

###############################################
############### Staging section ##################
###############################################

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy to staging'
  environment:
    name: stage
    url: https://beta.example.com

###############################################
############### Production section ##################
###############################################

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
    - master
  script:
    - echo 'Deploy to production'
  environment: #куда деплоить 
    name: production
    url: https://example.com
