---
image: gitlab/dind

stages:
  - build
  - test
  - review
  - stage
  - production


variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'

before_script:
  - cd reddit
  - bundle install

###############################################
############### Build section ##################
###############################################

build_ui_job:
  stage: build
  script:
    - docker build -t marbax/ui:test ui/

build_crawler_job:
  stage: build
  script:
    - docker build -t marbax/crawler:test crawler/

###############################################
############### Test section ##################
###############################################

test_ui_job:
  stage: test
  services:
    - name: mongo:latest
      alias: mongo-ui
  script:
    - python -m unittest discover -s tests/
    - coverage run -m unittest discover -s tests/
    - coverage report --include ui/ui.py

test_crawler_job:
  stage: test
  services:
    - name: mongo:latest
      alias: mongo-crawler
    - name: rabbitmq:latest
      alias: rabbitmq-crawler
  script:
    - python -m unittest discover -s tests/ 
    - coverage run -m unittest discover -s tests/ 
    - coverage report --include crawler/crawler.py

###############################################
############### Review section ##################
###############################################

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

branch review:
  stage: review
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
   name: branch/$CI_COMMIT_REF_NAME
   url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

###############################################
############### Staging section ##################
###############################################

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: https://beta.example.com

###############################################
############### Production section ##################
###############################################

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment: #куда деплоить 
    name: production
    url: https://example.com
