---
image: docker:stable
  #image: python:3.5

stages:
  - build
  - test
  - review
  - stage
  - production


variables:
  #DATABASE_URL: 'mongodb://mongo/user_posts'
  REGISTRY_URL: http://192.168.88.12/
  DOCKER_DRIVER: overlay2
  PROJECT_NAME: crawler

#before_script:
#  - sudo docker info
#  - python --version 
#  - python3 --version
#  - pip -V 
#  - pip2 -V 
#  - pip3 -V 
#  - pip3 install --upgrade pip && pip3 install flask==0.12.2 gunicorn==19.7.1 structlog==17.2.0 pymongo==3.5.1 requests==2.18.4 prometheus_client==0.1.0 uuid beautifulsoup4==4.6.0 pika==0.11.0 coverage==4.4.2 mongomock==3.8.0
#  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $CI_JOB_TOKEN $REGISTRY_URL

###############################################
############### Build section ##################
###############################################

build_ui_job:
  stage: test
  image: docker:stable
  environment:
    name: testing/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master
    - tags
  script:
    - echo "Building ui in $CI_ENVIRONMENT_SLUG"
    - docker build -t marbax/ui:test ui/

build_crawler_job:
  stage: test
  image: docker:stable
  environment:
    name: testing/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master
    - tags
  script:
    - echo "Building crawler in $CI_ENVIRONMENT_SLUG"
    - docker build -t marbax/crawler:test crawler/

###############################################
############### Test section ##################
###############################################

test_ui_job:
  stage: build
  image: python:alpine
  environment:
    name: testing/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master
    - tags
  services:
    - name: mongo:latest
      alias: mongo-ui
  script:
    - echo "Testing ui in $CI_ENVIRONMENT_SLUG"
    - pip3 install -r ui/requirements.txt -r ui/requirements-test.txt
    - export MONGO=mongo-ui
    - export MONGO_PORT=27017
    - cd ui && python3 -m unittest discover -s tests/
    - coverage3 run -m unittest discover -s tests/
    - coverage3 report --include ui/ui.py

test_crawler_job:
  stage: build
  image: python:3.5
  environment:
    name: testing/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master
    - tags
  services:
    - name: mongo:latest
      alias: mongo-crawler
    - name: rabbitmq:latest
      alias: rabbitmq-crawler
  script:
    - echo "Testing crawler in $CI_ENVIRONMENT_SLUG"
    - pip3 install --upgrade pip && pip3 install flask==0.12.2 gunicorn==19.7.1 structlog==17.2.0 pymongo==3.5.1 requests==2.18.4 prometheus_client==0.1.0 uuid beautifulsoup4==4.6.0 pika==0.11.0 coverage==4.4.2 mongomock==3.8.0
    - python3 -m unittest discover -s crawler/tests/ 
    - coverage run -m unittest discover -s crawler/tests/ 
    - coverage report --include crawler/crawler/crawler.py

###############################################
############### Review section ##################
###############################################

deploy_dev_job:
  stage: test
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

branch review:
  stage: test
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master
    - tags

###############################################
############### Staging section ##################
###############################################

staging:
  stage: test
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy to staging'
  environment:
    name: stage
    url: https://beta.example.com

###############################################
############### Production section ##################
###############################################

production:
  stage: test
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
    - master
  script:
    - echo 'Deploy to production'
  environment: #куда деплоить 
    name: production
    url: https://example.com
