---
image: python:3.5

stages:
  - build
  - test
  - review
  - stage
  - production


variables:
  #DATABASE_URL: 'mongodb://mongo/user_posts'
  DOCKER_DRIVER: overlay2
  PROJECT_NAME: crawler

before_script:
#  - docker login -u marbax -p Nikniknik1994MNE
  - pip3 install --upgrade pip && pip3 install flask==0.12.2 gunicorn==19.7.1 structlog==17.2.0 pymongo==3.5.1 requests==2.18.4 prometheus_client==0.1.0 uuid beautifulsoup4==4.6.0 pika==0.11.0 coverage==4.4.2 mongomock==3.8.0

###############################################
############### Build section ##################
###############################################

#build_ui_job:
#  stage: build
#  script:
#    - docker build -t marbax/ui:test ui/

#build_crawler_job:
#  stage: build
#  script:
#    - docker build -t marbax/crawler:test crawler/

###############################################
############### Test section ##################
###############################################

#test_ui_job:
#  stage: test
#  services:
#    - name: mongo:latest
#      alias: mongo-ui
#  script:
#    - python3 -m unittest discover -s src/ui/tests/
#    - coverage run -m unittest discover -s src/ui/tests/
#    - coverage report --include src/ui/ui/ui.py

test_crawler_job:
  stage: test
  services:
    - name: mongo:latest
      alias: mongo-crawler
    - name: rabbitmq:latest
      alias: rabbitmq-crawler
  script:
    - python3 -m unittest discover -s tests/ 
    - coverage run -m unittest discover -s tests/ 
    - coverage report --include crawler/crawler.py

###############################################
############### Review section ##################
###############################################

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

branch review:
  stage: review
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
   name: branch/$CI_COMMIT_REF_NAME
   url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

###############################################
############### Staging section ##################
###############################################

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: https://beta.example.com

###############################################
############### Production section ##################
###############################################

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment: #куда деплоить 
    name: production
    url: https://example.com
