---
# https://docs.gitlab.com/omnibus/docker/README.html
web:
  image: 'gitlab/gitlab-ce:${GITLAB_VERSION}'
  restart: always
  hostname: 'gitlab.crawler'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://${EXTERNAL_URL}' # внешний ИП
  ports:
    - '${HTTP_PORT}:80'
    - '${HTTPS_PORT}:443'
    - '${SSH_PORT}:22'
  volumes:
    - '/srv/gitlab/config:/etc/gitlab' # For storing the GitLab configuration files
    - '/srv/gitlab/logs:/var/log/gitlab' # For storing logs
    - '/srv/gitlab/data:/var/opt/gitlab' # For storing application data
