---
#https://docs.docker.com/compose/install/
version: '3.3'
services:

  mongo_db:
    image: mongo:${MONGO_VER}
    restart: always
    volumes:
      - mongo_db:/data/db
    networks:
      back_net:
       aliases:
       - mongo_db
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.mongo-db
#    environment:
#      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  crawler-ui:
    image: ${DOCKER_USER}/crawler-ui:${UI_VER}
    restart: always
    ports:
      - ${UI_HOST_PORT}:${UI_APP_PORT}/tcp
    networks:
      back_net:
       aliases:
       - crawler-ui
      front_net:
       aliases:
       - crawler-ui
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.crawler-ui
#    environment:
#      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    depends_on:
      - mongo_db

  crawler-app:
    image: ${DOCKER_USER}/crawler-app:${CRAWLER_VER}
    restart: always
    ports:
      - ${APP_HOST_PORT}:${APP_APP_PORT}/tcp
    networks:
      back_net:
       aliases:
       - crawler-app
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.crawler-app
#    environment:
#      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    depends_on:
      - mongo_db
      - rabbit_mq

  rabbit_mq:
    image: rabbitmq:${RABBIT_MQ_VER}
    restart: always
    hostname: ${QUEUE_NAME}}
    volumes:
      - rabbit_mq:/var/lib/rabbitmq
    networks:
      back_net:
       aliases:
       - rabbit_mq
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.rabbit-mq
    environment:
#      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASSWORD}

volumes:
  mongo_db:
  rabbit_mq:

networks:
  back_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.10.0/24
  front_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.11.0/24
