version: '3'
services:

  elasticsearch:
    image: elasticsearch:${ELASTIC_VERSION}
    restart: always
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic-data1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      back_net:
       aliases:
       - elasticsearch

  fluentd:
    restart: always
    image: ${DOCKER_USER}/fluentd:${FLUENTD_VERSION}
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      back_net:
        aliases:
          - fluentd
      front_net:
        aliases:
          - fluentd
    depends_on:
      - elasticsearch

  kibana:
    restart: always
    image: kibana:${KIBANA_VERSION}
    ports:
      - "${KIBANA_PORT}:5601"
    networks:
      back_net:
        aliases:
          - kibana
    depends_on:
      - fluentd

# не видит сервисов
#  zipkin:
#    restart: always
#    image: openzipkin/zipkin:2.12.6
#    ports:
#      - "9411:9411"
#    networks:
#      back_net:
#        aliases:
#          - zipkin
#      front_net:
#        aliases:
#          - zipkin

volumes:
  elastic-data1:

networks:
  front_net:
      driver: bridge
      ipam:
        config:
          - subnet: 10.0.10.0/24
  back_net:
      driver: bridge
      ipam:
        config:
          - subnet: 10.0.11.0/24
