---
  # все фигня ,нужно свой запилить,когда то
global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'email'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#nikita_morozov'
        send_resolved: true
  - name: 'email'
    email_configs:
      - to: 'ss@domain.tld'
        send_resolved: true
        from: 'ss@domain.tld'
        smarthost: 'smtp.yandex.ru:587'
        auth_username: 'alert@domain.tld'
        auth_password: 'SecRetPas$$word'
