---
# https://docs.gitlab.com/omnibus/docker/README.html
version: '3.3'
services:

  runner:
    env_file: .env
    image: gitlab/gitlab-runner:latest
    restart: always
    volumes:
      - runner:/etc/gitlab-runner 
      - /var/run/docker.sock:/var/run/docker.sock 
    networks:
      back_net:
       aliases:
       - runner
    environment:
    - CI_SERVER_URL=http://192.168.88.12/
    - RUNNER_NAME=crawler-runner
    - REGISTRATION_TOKEN=pn_6afCNnncRD-5P4Jnv
    - REGISTER_NON_INTERACTIVE=false

volumes:
  runner:

networks:
  back_net: